apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-api-base-cadastral
  namespace: dados-cadastrais
spec:
  selector:
    matchLabels:
      app: dc-api-base-cadastral
  replicas: 1
  template:
    metadata:
      labels:
        app: dc-api-base-cadastral
        squad: dadoscadastrais
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: dc-api-consulta-cadastral-key-teste
      containers:
      - name: dc-api-base-cadastral
        image: gcr.io/bvs-main-98cb/api-base-cadastral-dev:v1.2
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        - containerPort: 5155
          name: as-400 
        readinessProbe:
           httpGet:
            path: /api/health
            port: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: dc-api-base-cadastral
  namespace: dados-cadastrais
  annotations: 
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - name: http    
    port: 80
    protocol: TCP
    targetPort: 3333
  - name: as400
    protocol: TCP
    port: 5555
    targetPort: 5155
  selector:
    app: dc-api-base-cadastral
  type: LoadBalancer
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: dc-api-base-cadastral-socket
#  namespace: dados-cadastrais
#spec:
#  ports:
#  - name: as400
#    protocol: TCP
#    port: 5155
#    targetPort: 5155
#  selector:
#    app: dc-api-base-cadastral
#  type: NodePort
