#cadastral-api
FROM openjdk:8-jdk-alpine
LABEL maintainer="BVS.CORP.BIGDATA"

ARG JAR_FILE=rest-api-v1/target/rest-api-v1-1.1.jar
ARG EXPOSE_PORT=3333

VOLUME /tmp
EXPOSE ${EXPOSE_PORT}
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]