app:
  contexto-list:
      telefone:
        deParaServicos:
          COD_ORG: COD_ORGM
          MET_COD_CTT: MET_TELEFONE
          COD_TPO_CTT: COD_TIP_CTAT
          COD_CSS_CTT: COD_CLSS_CTAT
          DSC_CLSS_CTT: DSC_CLSS_CTAT
          DAT_ITL: DAT_INST
          DSC_STS_CTT: DSC_COND
          DSC_TPO_SIG: DSC_TIP_SGLO
          DSC_CTT: NUM_TEL
        deParaDominio:
          DSC_TIP_SGLO:
            campo: COD_TPO_SIG
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[sigilo]": 1
              "[nao sigilo]": 2
          COD_TIP_CTAT:
            campo: DSC_TPO_CTT
            dados:
              1: Fixo
              2: Celular
              3: Nextel
              4: PABX
              5: Fax
              6: Skype
              7: VOIP
              8: Outros
              9: Email
              10: Fixo Recado
              -3: Nao Informado
              -2: Nao se Aplica
              -1: Nao Identificado
          DSC_COND:
            campo: COD_STS_CTT
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[ativo]": 1
              "[inibido]": 2
              "[nao confirmado]": 3
              "[suspenso]": 4
      protocolo:
        deParaServicos:
          NUM_PRL_RCT: COD_PTCL_RCTA
          MET_PRL_STS_RCT: MET_COD_PTCL_RCTA_X_STATUS
          DAT_CST_RCT: DTH_CSTA
          MET_DAT_CST_RCT: MET_DTH_CSTA
          DSC_STS_RCT: DSC_STT_DCTO_RCTA
        deParaDominio:
          DSC_STT_DCTO_RCTA:
            campo: COD_STS_RCT
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[titular falecido]": 0
              "[regular]": 1
              "[cancelado]": 2
              "[pendente]": 3
              "[suspenso]": 4
              "[inexistente]": 5
              "[dados incompletos]": 6
              "[nulo]": 7
              "[nao especificado]": 9
              "[data nascimento invalida]": 8
      nome:
        deParaServicos:
          COD_ORG: COD_ORGM
          NUM_CPF: NUM_CPF_CNPJ
          MET_CPF: MET_NUM_CPF_CNPJ
          MET_NOM_PSS_FIS: MET_NOM_RAZ_SOC
          DAT_CAD: DTH_PROC_ORGM
      endereco:
        deParaServicos:
          COD_ORG: COD_ORGM
          MET_COD_EDR: MET_END
          COD_TPO_EDR: COD_TIP_ENDR
          DAT_INI_RSD: DAT_INI_RSID
          DAT_CAD: DTH_PROC_ORGM
          DAT_ULT_ALT: DTH_INCL_REG
          SGL_TPO_LGR: ENDR_TIP_LGDO
          NOM_LGR: ENDR_CPTO
          NUM_LGR: ENDR_NRO
          DSC_CPT: ENDR_CMPL
          NOM_BRO: ENDR_NOM_BAI
          NUM_CEP: ENDR_CEP
          NOM_CDD: ENDR_NOM_MNCP
          COD_EST: UF
          NUM_LTT: ENDR_LTTD
          NUM_LGT: ENDR_LGTD
          COD_SET_CNS_2000: STR_SENSO_2000
          COD_SET_CNS_2010: STR_SENSO_2010
      endereco_new:
        deParaServicos:
          COD_ORG: COD_ORGM
          MET_COD_EDR: MET_END
          COD_TPO_EDR: COD_TIP_ENDR
          DAT_INI_RSD: DAT_INI_RSID
          DAT_CAD: DTH_PROC_ORGM
          DAT_ULT_ALT: DTH_INCL_REG
          SGL_TPO_LGR: ENDR_TIP_LGDO
          NOM_LGR: ENDR_CPTO
          NUM_LGR: ENDR_NRO
          DSC_CPT: ENDR_CMPL
          NOM_BRO: ENDR_NOM_BAI
          NUM_CEP: ENDR_CEP
          NOM_CDD: ENDR_NOM_MNCP
          COD_EST: UF
          NUM_LTT: ENDR_LTTD
          NUM_LGT: ENDR_LGTD
          COD_SET_CNS_2000: STR_SENSO_2000
          COD_SET_CNS_2010: STR_SENSO_2010
        deParaDominio:
          COD_TIP_ENDR:
            campo: DSC_TPO_EDR
            dados:
              -3: Nao Informado
              -2: Nao se Aplica
              -1: Nao Identificado
              1: Residencial
              2: Comercial
              3: Publico
              4: Comunitario
              5: Outros
      end_instalacao:
        deParaServicos:
          NOM_LGR: ENDR_CPTO
          NUM_LGR: ENDR_NRO
          DSC_CPT: ENDR_CMPL
          NOM_BRO: ENDR_NOM_BAI
          NUM_CEP: ENDR_CEP
          NOM_CDD: ENDR_NOM_MNCP
          COD_EST: UF
          COD_ORG: ORIGEM
          DAT_CAD: DTH_PROC_ORGM
          DAT_ULT_ALT: DTH_INCL_REG
      sexo:
        deParaServicos:
          DSC_SEX: DSC_SEX_ORI
        deParaDominio:
          DSC_SEX_ORI:
            campo: COD_SEX
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[masculino]": 1
              "[feminino]": 2
      nacionalidade:
        deParaServicos:
          DSC_NAC: DSC_NCLD
          MET_DSC_NAC: MET_DSC_NCLD
      naturalidade:
        deParaServicos:
          SGL_EST_NSC: SIGLA_UF_NCTO
          DSC_NTR: DSC_NTLD
          MET_DSC_NTR: MET_DSC_NTLD
      nome_pais:
        deParaServicos:
          NOM_PAS_NSC: NOM_PAIS
          MET_NOM_PAS_NSC: MET_NOM_PAIS
      estado_civil:
        deParaServicos:
          DSC_EST_CIV: DSC_EST_CVL
          MET_COD_EST_CIV: MET_COD_EST_CVL
        deParaDominio:
          DSC_EST_CVL:
            campo: COD_EST_CIV
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[casado]": 1
              "[solteiro]": 2
              "[viuvo]": 3
              "[divorciado / desquitado]": 4
              "[separado]": 5
              "[companheiro / uniao estavel]": 6
              "[outros]": 9
      grau_instrucao:
        deParaServicos:
          DSC_GAU_ITC: DSC_GRAU_INST
          MET_COD_GAU_ITC: MET_COD_GRAU_INST
        deParaDominio:
          DSC_GRAU_INST:
            campo: COD_GAU_ITC
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[analfabeto]": 1
              "[ensino fundamental incompleto]": 2
              "[ensino fundamental completo]": 3
              "[ensino medio incompleto]": 4
              "[ensino medio completo]": 5
              "[superior incompleto]": 6
              "[superior completo]": 7
              "[pos graduacao completa]": 8
              "[pos graduacao incompleta]": 9
              "[mestrado completo]": 10
              "[mestrado incompleto]": 11
              "[doutorado completo]": 12
              "[doutorado incompleto]": 13
      classe_social:
        deParaServicos:
          DSC_CSS_SCL: DSC_CLASSE_SOCIAL
          MET_COD_CSS_SCL: MET_COD_CLSS_SOCL
        deParaDominio:
          DSC_CLASSE_SOCIAL:
            campo: COD_CSS_SCL
            dados:
              "[nao informado]": -3
              "[nao se aplica]": -2
              "[nao identificado]": -1
              "[e]": 1
              "[c]": 2
              "[a1]": 3
              "[d]": 4
              "[a2]": 5
              "[b1]": 6
              "[b2]": 7
      documento:
        deParaServicos:
          COD_ORG: COD_ORGM
          NUM_DOC: IDT_PRI_DCTO
          DSC_TPO_DOC: DSC_TIP_DCTO
          NOM_OGA_EMS: IDT_ORG_EMSS_DCTO
          DAT_EMS: DAT_EMSS_DCTO
          COD_EST_EMS: SIGLA_UF_EMSS_DCTO
          NUM_SER_DOC: NUM_SRIE_DCTO
          NUM_ZON: NUM_ZNA_TITL_ELTR
          NUM_SEC: NUM_SEC_TITL_ELTR
          DSC_SIT_DOC: DSC_SIT_TITL_ELTR
          DSC_LCL_VOT: NOM_LOCL_VOTA
          DSC_EDR_VOT: ENDR_CPTO_VOTA
          NOM_BRO_VOT: BAI_VOT_ELEI
          NOM_CDD_VOT: MUN_VOT_ELEI
          COD_EST_VOT: SGL_UF_VOTA
          DAT_ATL_VOT: DAT_ATLZ_VOTA
          DAT_CAD: DTH_PROC_ORGM
        deParaDominio:
          DSC_TIP_DCTO:
            campo: COD_TPO_DOC
            dados:
              "[rg]": 1
              "[titulo eleitor]": 2
              "[cpf]": 3
              "[passaporte]": 4
              "[rne]": 5
              "[carteira profissional]": 6
      ocupacao:
        deParaServicos:
          MET_COD_PRO: MET_OCUPACAO
          COD_PRO: COD_OCP
          DSC_PRO: DSC_OCUPACAO
      receita_pj:
        deParaServicos:
          CNPJ: NUM_CPF_CNPJ
          RET_CONSULTA: RET_CNSLT
          DT_ABRT: DT_ABERT
          RAZAO_SOC: NOM_RAZ_SOC
          NOM_FNTS: NOM_FNTS
          COD_NAT_JUR: NAT_JUR
          CNAE: CNAE_PRINCIPAL
          TP_LOGR: TIP_LOGR
          LOGRADOURO: NOM_LOGR
          NUMERO: NUM_LOGR
          COMPLEMENTO: CPLM_LOGR
          CEP: NUM_CEP
          BAIRRO: NOM_BAI
          COD_MNCP: COD_MNCP
          MUNICIPIO: NOM_MNCP
          UF: UF
          EMAIL: END_CORR_ELTR
          TELEFONE: NUM_TEL
          ENTE_FED_RESP: UF_RSP
          SIT_CAD: SIT_CAD
          DT_SIT_CAD: DT_SIT_CAD
          MOT_SIT_CAD: MTV_SIT_CAD
          SIT_ESP: SIT_ESP
          DT_SIT_ESP: DT_SIT_ESP
          MATRIZ: FLAG_MTRZ
          DTH_CNSLT: DTH_CNSLT_RF
          RSVD: RESERVADO
          PORTE: PRT_CNPJ
          ORIGEM: COD_ORGM
      opcao_mei:
        deParaServicos:
          CNPJ: NUM_CPF_CNPJ
          RET_CONSULTA: RET_CNSLT
          PORTE: PRT_CNPJ
          OPCAO_PELO_SIMPLES: OPC_SMPL
          DATA_OPCAO_PELO_SIMPLES: DT_OPC_SMPL
          DATA_EXCLUSAO_SIMPLES: DT_EXCL_SMPL
          OPCAO_MEI: OPC_MEI
          DATA_HORA_CONSULTA: DTH_CNSLT
          ORIGEM: COD_ORGM
      ccm:
         deParaServicos:
           STATUS: STT_CNPJ
           CNPJ: NUM_CPF_CNPJ
           INSCRICAO_MUNICIPAL: NUM_INSC_MNCP
           EMPRESA: EMP
           TIPO_PESSOA_JURIDICA: TIP_PESS
           TIPO_UNIDADE: TIP_UND
           ENDERECO_LOCALIZACAO: END_CPTO
           BAIRRO: NOM_BAIR
           CEP: NUM_CEP
           TELEFONE: NUM_TEL
           INICIO_DATA: DT_ABERT
           DATA_INSCRICAO: DT_INSC_MNCP
           INSCRICAO_CENTRALIZADORA: INSC_CNTLZ
           TIPO_ENDERECO: TIP_LOGR
           NUMERO_IPTU: NUM_CRN_IPTU
           DATA_ATUALIZACAO: DT_ATLZ
           ATIVO: ATIVO
           DATA_CONSULTA: DT_CNSLT
           FONTE: COD_FONT
